// <auto-generated />
using System;
using BitirmeÖdevi_CarReservation.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable



// <auto-generated />
#nullable disable
namespace BitirmeÖdevi_CarReservation.Persistence.Migrations
{
    partial class AddTagCloudClean
    {
    }
}
